
# # Create source plates for media preparation using biomek


# The notebook also generates files with instructions on how to prepare source plates with stock solutions, culture, antiobiotics.


# Tested using **ART 3.9.4** kernel on jprime.lbl.gov


# ## Inputs and outputs


# #### Required files to run this notebook:
#    
#    - `../data/flaviolin/stock_concentrations.csv` 
#    


# #### Files generated by running this notebook:
# 
# 
#    - `24-well_stock_plate_high.csv`, `24-well_stock_plate_low.csv` - instructions on how to prepare the source plates
#    
#    - `24-well_stock_plate_fresh.csv` - the plate that includes components that need to be prepared fresh for every cycle (culture, FeSO4)
#     
# The files are stored in the user defined directory. 


# ## Setup


# Importing needed libraries:


import os
import sys
sys.path.append('../')

import pandas as pd
import numpy as np



# ## User parameters


user_params = {
    'stock_conc_file': '../data/flaviolin/stock_concentrations.csv',
    'output_path': f'../data/flaviolin/',  # Path for output files
}


# Load the stock concentrations


df_stock = pd.read_csv(user_params['stock_conc_file'])
df_stock = df_stock.set_index("Component")


df_stock


# ## Create stock solutions plate dataframe
# 


df_stock_plate = pd.DataFrame(
    columns=["Component", "Stock", "Concentration[mM]"])
    
i = 0
num_comp = len(df_stock)
for i in range(2*num_comp):

    if i < num_comp:
        component = df_stock.index[i]
        df_stock_plate.loc[i] = [
            component, 
            "high",
            df_stock.loc[component]["High Concentration[mM]"]
        ]
    elif i < 2*num_comp:
        component = df_stock.index[(i-num_comp)]
        if df_stock.loc[component]["Dilution Factor"] > 1.0:
            df_stock_plate.loc[i] = [
                component, 
                "low",
                df_stock.loc[component]["Low Concentration[mM]"]
            ]
            
df_stock_plate.reset_index(drop=True, inplace=True)


df_stock_plate


# Split the components into two source plates - one with high concentration levels and the other one with low levels


# #### High level


df_stock_plate_high = df_stock_plate.copy()
df_stock_plate_high = df_stock_plate_high[df_stock_plate_high['Stock']=='high']
df_stock_plate_high.drop(columns='Stock', inplace=True)



# Remove FeSO4 from this plate:


df_stock_plate_high.drop(df_stock_plate_high[df_stock_plate_high['Component']=='FeSO4'].index, inplace=True)



# Create additional wells of MgCl2 and NaCl, as those components will be used in larger volumes:


df_stock_plate_high = df_stock_plate_high.append(df_stock_plate_high[df_stock_plate_high['Component']=='MgCl2'], ignore_index=True)
df_stock_plate_high = df_stock_plate_high.append(df_stock_plate_high[df_stock_plate_high['Component']=='NaCl'], ignore_index=True)


df_stock_plate_high


# Assign well names:


num_source_wells = len(df_stock_plate_high) 

source_well_type = '24-well'
well_rows = 'ABCD'
well_columns = '123456'
    
well_names = [f'{row}{column}' for column in well_columns for row in well_rows]
well_names = well_names[:num_source_wells]

df_stock_plate_high.reset_index(drop=True, inplace=True)
df_stock_plate_high['Well'] = well_names
df_stock_plate_high = df_stock_plate_high.set_index(['Well'])
df_stock_plate_high


# #### Low level


df_stock_plate_low = df_stock_plate.copy()
df_stock_plate_low = df_stock_plate_low[df_stock_plate_low['Stock']=='low']
df_stock_plate_low.drop(columns='Stock', inplace=True)
df_stock_plate_low.drop(df_stock_plate_low[df_stock_plate_low['Component']=='FeSO4'].index, inplace=True)
df_stock_plate_low


# Assign well names:


num_source_wells = len(df_stock_plate_low) 

well_names = [f'{row}{column}' for column in well_columns for row in well_rows]
well_names = well_names[:num_source_wells]

df_stock_plate_low.reset_index(drop=True, inplace=True)
df_stock_plate_low['Well'] = well_names
df_stock_plate_low = df_stock_plate_low.set_index(['Well'])
df_stock_plate_low


# #### Fresh stocks plate


# Create a plate with fresh stocks of FeSO4 and culture:


fe_low = df_stock_plate[(df_stock_plate['Component']=='FeSO4') & (df_stock_plate['Stock']=='low')]['Concentration[mM]'].values[0]
fe_high = df_stock_plate[(df_stock_plate['Component']=='FeSO4') & (df_stock_plate['Stock']=='high')]['Concentration[mM]'].values[0]

df_stock_plate_fresh = pd.DataFrame(data=[['A1', 'Culture', ''], ['B1', 'FeSO4', fe_low], ['C1', 'FeSO4', fe_high]],
                                    columns=['Well', 'Component', 'Concentration[mM]'], 
                                    )
df_stock_plate_fresh =df_stock_plate_fresh.set_index("Well")
df_stock_plate_fresh


# ## Save source plate instructions:


stock_plate_file = f"{user_params['output_path']}/{source_well_type}_stock_plate_high.csv"
df_stock_plate_high.to_csv(stock_plate_file)


stock_plate_file = f"{user_params['output_path']}/{source_well_type}_stock_plate_low.csv"
df_stock_plate_low.to_csv(stock_plate_file)


stock_plate_file = f"{user_params['output_path']}/{source_well_type}_stock_plate_fresh.csv"
df_stock_plate_fresh.to_csv(stock_plate_file)





