# 
# # Calculate low and high stock solutions concentrations given standard media recipe

# 
# This notebook calculates stock concentrations for a media optimization project. Given a standard media recipe, ranges for intervals to be explored, the notebook generates sets of low and high concentrations such that media preparation can be done without dilutions (which reduces the number of operations, hence time, and the number of pipette tips needed). 
# 

# 
# Tested using **ART 3.9.4** kernel on jprime.lbl.gov

# 
# ## Inputs and outputs

# 
# #### Required file to run this notebook:
#    - `../data/flaviolin/standard_recipe_concentrations.csv`
#    
#    A file with the standard media recipe, with same units for each component in [mM]. This file also contains a column with **solubility limits** for each component. 
#    
#    Note that in this study, the target concentration for Kanamycin is given as dilution factor (e.g. 1x).
#    
# An example of the file content:
# 
# | Component | Concentration[mM]   | Solubility[mM]
# |------|------|------|
# |   MOPS  | 40 | 2389.37 |
# | H3BO3 | 0.004 | 700 |
# | K2SO4 | 0.29 | 636.98 |
# 

# 
# #### Files generated by running this notebook:
# 
#    - `stock_concentrations.csv`
#    
#    - `bounds_file.csv` (optionally, the file with bounds for ART is created)
#  
#    The files are stored in the user defined directory.

# 
# ## Setup

# 
# Importing needed libraries:


import sys
sys.path.append('../')

import string
import pandas as pd
import numpy as np
import scipy

from pyDOE import lhs

from core import find_volumes, check_solubility, find_volumes_bulk

# 
# ### User parameters


user_params = {
    'standard_media_file': '../data/flaviolin/standard_recipe_concentrations.csv',  
    'output_file_path': '../data/flaviolin/', # Folder for output files
    'factor_range': 10,             # How many times higher/lower values from the 
    # standard media you want to explore? If you want to explore different 
    # relative ranges across components, you can specify it below (see cell 6)
    'bounds_file': '../data/flaviolin/Putida_media_bounds.csv', # name of the file with bounds needed for ART
    'well_volume': 1500,            # Total volume of the media content+culture in the well
    'min_volume_transfer': 5,       # Minimal transfer volume of the liquid handler
    'culture_factor': 100,          # Dilution factor for culture, e.g. 100x, 1000x
    } 


culture_volume = user_params['well_volume'] / user_params['culture_factor']


# 
# Read the standard media recipe concentrations


df_stand = pd.read_csv(user_params['standard_media_file'])
df_stand = df_stand.set_index("Component")

# 
# Assign exploration ranges for each component. A factor of 1.5 means we want to explore values 50% higher and 50% lower than the values from the standard recipe.

# 
# First, the value from `user_params['factor_range']` is assigned to all components. 


num_components = len(df_stand)
df_stand['Factor'] = user_params['factor_range']* np.ones(num_components)

# 
# Individual values then can be modified if needed.


df_stand.at['MOPS[mM]', 'Factor'] = 1.0
df_stand.at['Tricine[mM]', 'Factor'] = 1.0
df_stand.at['Glucose[mM]', 'Factor'] = 1.0
df_stand.at['K2HPO4[mM]', 'Factor'] = 5.0
df_stand.at['NH4Cl[mM]', 'Factor'] = 1.5
df_stand.at['Kan', 'Factor'] = 1.

# 
# Define target low and high concentration levels:


target_conc_low = df_stand['Concentration'] / df_stand['Factor']
conc_low_round = np.array([round(conc,6) for conc in list(target_conc_low)])
target_conc_low = conc_low_round
target_conc_high = df_stand['Concentration'] * df_stand['Factor']


target_conc_low

# 
# Save low and high levels of concentrations to a `bounds_file` file needed for ART.


if 'bounds_file' in user_params:
    df_bounds = pd.DataFrame(columns=['Variable', 'Min', 'Max'])
    df_bounds['Variable'] = df_stand.index
    df_bounds['Min'] = target_conc_low
    df_bounds['Max'] = target_conc_high.values
    df_bounds = df_bounds.set_index('Variable')
    df_bounds = df_bounds[df_stand['Factor'] > 1.]
    df_bounds.to_csv(path_or_buf=user_params['bounds_file'])
    display(df_bounds)

# 
# ## Find a set of low level stock concentrations that can achieve the lowest levels of target concentrations

# 
# $$c_s=\frac{c_{t_{\min}} \cdot V_\text{well}}{V_{\min}}$$


min_tip_volume = user_params['min_volume_transfer']
df_low = pd.DataFrame(
    index=df_stand.index,
    columns=["Stock Concentration", "Target Concentration"])
df_low["Target Concentration"] = target_conc_low
df_low["Stock Concentration"] = df_low["Target Concentration"]*user_params['well_volume']/min_tip_volume
df_low

# 
# ### Check solubility 

# 
# Increase the volume transfer, in increments of 5uL, for the components for which concenstrations are not soluble (there is no need to make minimal volume transfers)

# 
# $$c^i_{s}=\frac{c^i_{t_{\min}} \cdot V_\text{well}}{V_{\min}+5}$$


if 'Solubility' in df_stand.columns:
    
    nonsol_comp_low = check_solubility(df_low, solubility=df_stand['Solubility'])
    volume_transfer = min_tip_volume

    i = 0
    while len(nonsol_comp_low) > 0:    
        print(f'  Iteration {i}\n')
        volume_transfer += min_tip_volume

        for comp in nonsol_comp_low:
            df_low.at[comp,"Stock Concentration"] = df_low.at[
                comp,"Target Concentration"
            ]*user_params['well_volume']/volume_transfer

        nonsol_comp_low = check_solubility(df_low, solubility=df_stand['Solubility'])
        i += 1
    
else:
    print('Solubility values are not provided and it is assumed the limits are not reached.')
    

# 
# Check if all volumes are larger than the minimal transfer volume (5 uL)


EPS = 0.000001
volumes, df = find_volumes(
    user_params['well_volume'], 
    components=df_low.index,
    stock_conc_val=df_low['Stock Concentration'].values, 
    target_conc_val=df_low['Target Concentration'].values,
    culture_ratio=user_params['culture_factor']
)
assert (df['Volumes[uL]'].values >= min_tip_volume - EPS).all(), f"Not all volumes are >={min_tip_volume}uL!"


df

# 
# Round to 5 digits after decimal point


num_digits = 6
conc = np.array([round(num, num_digits) for num in list(df_low['Stock Concentration'].values)])
df_low['Stock Concentration'] = conc


# 
# ## Find a set of high level stock concentrations that can achieve the highest levels of target concentrations

# 
# Find stock concentrations for the upper limit in the range to explore.


df_high = df_low.copy()
df_high["Target Concentration"] = target_conc_high
df_high["Solubility"] = df_stand['Solubility']

# 
# Check if there are feasible volumes for the low level concentrations found above:


try:
    volumes, df = find_volumes(
        user_params['well_volume'],
        components=df_high.index,
        stock_conc_val=df_high['Stock Concentration'].values, 
        target_conc_val=df_high['Target Concentration'].values,
        culture_ratio=user_params['culture_factor']
    )
    feasible_volumes = True
    assert (df['Volumes[uL]'].values >= min_tip_volume - EPS).all(), f"Not all volumes are >={min_tip_volume}uL!"
except AssertionError:
    feasible_volumes = False
    print("No feasible volumes are found!")
    

# 
# ### Find feasible volumes

# 
# Increase the current stock concentrations, by 5-fold increments, of components which are the furthest away from the solubility limit  


if not feasible_volumes:
    print("No feasible volumes")
    
    MULTIPL_FACTOR = 5

    success = False
    df = df_high.copy()

    i = 0
    while success is False:
        i += 1

        # Find ratios of solubility over current stock concentrations
        df['Ratio'] = df['Solubility'].values / df['Stock Concentration'].values

        # Find which component is the furthest away from the solubility limit 
        comp = df[df['Ratio'] > MULTIPL_FACTOR]['Ratio'].idxmax()

        # Increase the current stock concentration by a factor
        df.at[comp, 'Stock Concentration'] *= MULTIPL_FACTOR

        # Find if there are feasible volumes for such stock and target concentrations
        try:
            volumes, df_high = find_volumes(
                user_params['well_volume'], 
                components=df.index,
                stock_conc_val=df['Stock Concentration'].values, 
                target_conc_val=df['Target Concentration'].values,
                culture_ratio=user_params['culture_factor']
            )
            success = True
            if success:
                print(f'Iteration {i}:')
                print('Success!')
        except:
            pass
else:
    df_high = df.copy()
    
df_high["Solubility"] = df_stand['Solubility']


# 
# See what are the calculated volumes


df_high

# 
# ### Correct for minimal transfer volumes

# 
# If there are volumes that are smaller than the minimum transfer volume, change stock concentrations for those components (decrease the concentrations so that the volume increases).


# Find components with volume transfers smaller than the minimal
comp_small_vol = df_high[
    df_high['Volumes[uL]'] < min_tip_volume - EPS
].index
print(f"{len(comp_small_vol)} component(s) found with volume transfers smaller than the minimal")

# Define new volume transfer to be higher than the minimal, so there is some flexibility
NEW_VOLUME_TRANSFER = 5.0*min_tip_volume

for comp in comp_small_vol:
    factor_diff =  NEW_VOLUME_TRANSFER / (df_high.at[comp, 'Volumes[uL]'])
    print(f'Decreasing the concentration of {comp} by {factor_diff} times')
    df_high.at[comp, 'Stock Concentration'] /= factor_diff
    

# 
# Recalculate volumes for corrected stock concentrations:


volumes, df_high_new = find_volumes(
    user_params['well_volume'], 
    components=df_high.index,
    stock_conc_val=df_high['Stock Concentration'].values, 
    target_conc_val=df_high['Target Concentration'].values,
    culture_ratio=user_params['culture_factor']
)
df_high_new

# 
# Round to 5 digits after decimal point


df_high = df_high_new.copy()
num_digits = 5
conc = np.array([round(num, num_digits) for num in list(df_high['Stock Concentration'].values)])
df_high['Stock Concentration'] = conc


# 
# Create the final dataframe with low and high concentrations and dilution factor for their preparation


df_stock = df_low.copy()
df_stock.rename(columns={'Stock Concentration': 'Low Concentration'}, inplace=True)
df_stock = df_stock.drop(['Target Concentration'], axis='columns')
df_stock['High Concentration'] = df_high['Stock Concentration']
df_stock['Dilution Factor'] = df_stock['High Concentration']/df_stock['Low Concentration']
df_stock

# 
# ### Test found stock concentrations for different, randomly chosen, target concentrations

# 
# Create random target concentrations, sampled using Latin Hypercube, given lower/upper bounds:


n_samples = 100

latin_hc = lhs(
    len(df_stock), samples=n_samples, criterion="maximin"
)

lb = target_conc_low.ravel()
ub = target_conc_high.ravel()

target_conc_val = lb + latin_hc * (ub - lb)

df_target_conc = pd.DataFrame(
    data=target_conc_val, 
    columns=target_conc_high.index
)

# 
# Check what are the volumes for random choices of target concentrations within the given ranges:


df_volumes = find_volumes_bulk(
    df_stock, 
    df_target_conc=df_target_conc, 
    well_volume=user_params['well_volume'],
    min_tip_volume=min_tip_volume,
    culture_ratio=user_params['culture_factor'],
    verbose=0
)


df_target_conc

# 
# ### Save the file with stock concentrations


num_digits = 2
dil_fact = np.array([round(num, num_digits) for num in list(df_stock['Dilution Factor'].values)])
df_stock['Dilution Factor'] = dil_fact

# 
# Emphasize that kanamycin stock is given in terms of dilution factor:


kan_stock_low = df_stock.at['Kan', 'Low Concentration']
kan_stock_high = df_stock.at['Kan', 'High Concentration']
df_stock.at['Kan'] = [f'{kan_stock_low:.0f}x', f'{kan_stock_high:.0f}x', 1.]
df_stock


stock_conc_file = f'{user_params["output_file_path"]}stock_concentrations.csv'


df_stock.to_csv(stock_conc_file)





