
# # Create media designs for DBTL 1 and DBTL 2


# This notebook generates the initial media designs. We use ART's capability to provide initial designs for media components for which to get phenotypic data. These designs and phenotypic data will be used later to predict new designs. 
# 
# As this is the initial round of designs, we use Latin Hypercube sampling.
# 
# 
# We include a desing that is very close to the standard media (up to 10% variation for each component), as a control for every cycle.


# Tested using **ART 3.9.4** kernel on jprime.lbl.gov


# ## Inputs and output


# **Required file to run this notebook:**
# - `Putida_media_bounds.csv`
# - `standard_recipe_concentrations.csv`


# **File generated by running this notebook**
# - `recommendations_initial.csv`


# The files are stored in the user defined directory. 


# ## Setup


# Clone the git repository with the `ART` library 
# 
# `git clone https://github.com/JBEI/AutomatedRecommendationTool.git`  
# <!-- <font color='red'> _____ -->
# <!-- **WE SHOULD TALK ABOUT LICENSING HERE!!!** </font> -->
# 
# or pull the latest version. 
# 
# Information about licensing ART is available at https://github.com/JBEI/ART.
# 
# Importing needed libraries:


import sys
sys.path.append('../../AutomatedRecommendationTool')        # Make sure this is the location for the ART library 
sys.path.append('../')
    
from art.core import * 
import matplotlib.pyplot as plt



# ## User parameters


# ### Defining media components and the number of instances (designs) to be created


CYCLE = 1

user_params = {
    'bounds_file': f'../data/flaviolin/Putida_media_bounds.csv',
    'output_file_path': f'../data/flaviolin/DBTL{CYCLE}', # Folder for output files,
    'standard_media_file': '../data/flaviolin/standard_recipe_concentrations.csv',
}


# Specify which components to explore:


user_params['components'] = [
    'H3BO3',
    'K2SO4',
    'K2HPO4',
    'FeSO4',
    'NH4Cl',
    'MgCl2',
    'NaCl',
    '(NH4)6Mo7O24',
    'CoCl2',
    'CuSO4',
    'MnSO4',
    'ZnSO4'
]


# Here we specify how many instances (designs) we want to create and how many replicates (change as desired). In this case we run two DBTL cycles with initial designs, 12 instances with 4 replicates for each, out of which one design is reserved for the control.


user_params['n_instances'] = 22
user_params['n_replicates'] = 4 


df_stand = pd.read_csv(user_params['standard_media_file']).set_index("Component")


df_stand


# ### Generate the control media 


# Control media will be uniformly drawn from the interval 90% to 110% around the standard recipe.


ub = 1.1
lb = 0.9
df_control = pd.DataFrame(columns=user_params['components'])

for component in user_params['components']:
    stand_conc = df_stand.loc[component]['Concentration[mM]']
    df_control.at[0, component] = stand_conc*np.random.uniform(lb, ub)
    df_control.at[1, component] = stand_conc*np.random.uniform(lb, ub)



df_control


# ### Random media


# Read bounds:


df_bounds = pd.read_csv(user_params['bounds_file'])


df_bounds


df_bounds_factor = pd.DataFrame(columns=['Variable', 'Min', 'Max'])
df_bounds_factor['Variable'] = user_params['components']
df_bounds_factor['Min'] = -1*np.ones(12)
df_bounds_factor['Max'] = np.ones(12)
df_bounds_factor


# Draw LH samples from [-1, 1]


# If [0, 1] map it to [1, 10] or [1, 5] or [1, 1.5].
# 
# If [-1, 0] map it to [1/10, 1] or [1/5, 1] or [1/1.5, 1].


mapping = lambda x, factor: 1 + -1*((1/factor) -1)*x if x < 0 else 1 + (factor-1)*x



bounds_factor_file = f'../data/flaviolin/Putida_media_bounds_factor.csv'


df_bounds_factor.to_csv(bounds_factor_file)


# Define a dictionary that contains the settings that ART will use to find the recommended designs:


art_params = {
    'input_vars': user_params['components'],
    'bounds_file': bounds_factor_file, # file with bounds# input variables, i.e. features
    'num_recommendations': user_params['n_instances'],    # one of them will be wild type
    'initial_cycle': True,                                    # Set this to True for initial designs recommendations
    'seed': 10,                                               # seed for number random generator
    'output_directory': user_params['output_file_path']  # directory to store this output
}



# With the configuration stored in `art_params`, we now run ART:


art = RecommendationEngine(**art_params)
df = art.recommendations.copy()
df.tail()


# Transform these bounds into our factors:


df_ranges_factors = df.copy()

factor = {}
for comp in (user_params['components']):
    factor[comp] = np.sqrt(
        df_bounds[df_bounds['Variable']==comp]['Max'] / df_bounds[df_bounds['Variable']==comp]['Min']
    )

for ind in df.index:
    for comp in df.columns:
        df_ranges_factors.at[ind, comp] = mapping(df.at[ind, comp], factor[comp])



df_ranges_factors.head()


# Transform these factors into our ranges:


df_ranges = df.copy()

for comp in df.columns:
    stand_conc = df_stand.loc[comp, 'Concentration[mM]']
    df_ranges.loc[:, comp] = stand_conc * df_ranges_factors.loc[:, comp]


df_ranges


# ## Cycle 1


df_target_1 = df_ranges.iloc[:11]
df_target_1 = df_target_1.append(df_control.iloc[0]).reset_index(drop=True)
df_target_1


df_target_2 = df_ranges.iloc[11:]
df_target_2 = df_target_2.append(df_control.iloc[1]).reset_index(drop=True)
df_target_2


# ### Checking the distribution of initial designs


def designs_pairwise(art, df):

    dim = art.num_input_var

    plt.style.use(["seaborn-talk"])

    fig = plt.figure(figsize=(35, 35))
    fig.patch.set_facecolor("white")

    X = df.values

    for var1 in range(dim):
        for var2 in range(var1 + 1, dim):

            ax = fig.add_subplot(dim, dim, (var2 * dim + var1 + 1))
            ax.scatter(
                X[:, var1],
                X[:, var2],
                c="r",
                edgecolor="r",
                marker="+",
                lw=1,
                label="Train data",
            )
            
            if var2 == (dim - 1):
                ax.set_xlabel(art.input_vars[var1])
            if var1 == 0:
                ax.set_ylabel(art.input_vars[var2])
                if var2 == 0:
                    ax.legend(loc="center left", bbox_to_anchor=(1, 0.5), shadow=True)

    fig.savefig(f'{art.outDir}/designs_pairwise.png', transparent=False, dpi=300
    )


designs_pairwise(art, df_ranges)


# ## Saving the generated designs


# Include all replicates: 


df_target_1 = df_target_1.loc[df_target_1.index.repeat(user_params['n_replicates'])]
df_target_2 = df_target_2.loc[df_target_2.index.repeat(user_params['n_replicates'])]



# Rename index to well names:


well_rows = 'ABCDEF'
well_columns = '12345678'


well_names = [f'{row}{column}'  for row in well_rows for column in well_columns]

df_target_1['Well'] = well_names
df_target_1 = df_target_1.set_index(['Well'])
df_target_1


file = f"{user_params['output_file_path']}/target_concentrations.csv"
df_target_1.to_csv(file)


df_target_2['Well'] = well_names
df_target_2 = df_target_2.set_index(['Well'])


file = f'../data/flaviolin/DBTL2/target_concentrations.csv'
df_target_2.to_csv(file)





